### ISSUE TITLE
Add project details to the "about" html page

### ISSUE THREAD

**Issue by ColinAnthony** [codebridge-za/seeking-shelter#27]
Add project details (from the first two sections of the readme.md - overview and contact details, as well as contributers)

**Comment by rikusv** [comment]
We can build the 'about' page using `README.md` directly, but then we'll need to use comments in the markdown to mark what should be excluded. For example:

```markdown
<!-- START_EXCLUDE -->
## Some header

Some paragraphs...
<!-- END_EXCLUDE -->
```

Happy with that?
